ProjectTimeLogger/ViewModels/Api/TimeLogModels.cs
namespace ProjectTimeLogger.ViewModels.Api
{
    public class TimeLogHoursModel
    {
        public string Name { get; set; }

        public float Hours { get; set; }
    }
}

ProjectTimeLogger/ViewModels/BaseSearchFormModel.cs
using ProjectTimeLogger.Db.Models.Search;
using ProjectTimeLogger.ViewModels.Contracts;

namespace ProjectTimeLogger.ViewModels
{
    public abstract class BaseSearchFormModel : IBaseSearchFormModel
    {
        public int RowCount = 10;

        public int? Page { get; set; }

        public string SortBy { get; set; }
        public bool? SortDesc { get; set; }

        protected virtual void SetSearchRequest(BaseRequest request)
        {
            if (this.Page < 1) { this.Page = null; }

            request.RowCount = this.RowCount;
            request.Offset = ((this.Page ?? 1) - 1) * this.RowCount;

            if (!string.IsNullOrWhiteSpace(this.SortBy))
            {
                request.SortDesc = this.SortDesc == true;
                request.SortColumn = this.SortBy;
            }
        }
    }
}

ProjectTimeLogger/ViewModels/BaseSearchModel.cs
using ProjectTimeLogger.Db.Models.Search;

namespace ProjectTimeLogger.ViewModels
{
    public abstract class BaseSearchModel<TSearchResponse, TSearchForm, T>
        where TSearchResponse : BaseResponse<T>
        where TSearchForm : BaseSearchFormModel
    {
        public TSearchResponse Response { get; set; }

        public TSearchForm SearchForm { get; set; }

        protected BaseSearchModel(TSearchForm searchForm)
        {
            this.SearchForm = searchForm;
        }

        public virtual Pager ToPager()
        {
            return new Pager(this.SearchForm.Page ?? 1, this.SearchForm.RowCount, this.Response.TotalRecords);
        }
    }
}

ProjectTimeLogger/ViewModels/Contracts/IBaseSearchFormModel.cs
namespace ProjectTimeLogger.ViewModels.Contracts
{
    public interface IBaseSearchFormModel
    {
        int? Page { get; set; }

        string SortBy { get; set; }

        bool? SortDesc { get; set; }
    }
}

ProjectTimeLogger/ViewModels/ErrorViewModel.cs
namespace ProjectTimeLogger.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectTimeLogger/ViewModels/Pager.cs
namespace ProjectTimeLogger.ViewModels
{
    public class Pager
    {
        private int MaxDisplayedPages = 10;

        public int Page { get; set; }

        public int ItemsPerPage { get; set; } = 10;

        public long TotalItemsCount { get; set; }

        public int PagesCount
        {
            get
            {
                var result = (int)Math.Ceiling(this.TotalItemsCount / (decimal)this.ItemsPerPage);

                return (result < 1) ? 1 : result;
            }
        }

        public List<int> DisplayedPages
        {
            get
            {
                var result = new List<int>();
                var maxPage = Math.Floor(TotalItemsCount / (double)ItemsPerPage);
                var start = Math.Max(this.Page - (int)Math.Floor(this.MaxDisplayedPages / (decimal)2), 1);
                var end = Math.Min((start - 1) + this.MaxDisplayedPages, this.PagesCount);

                for (var i = start; i <= end; i++)
                {
                    result.Add(i);
                }

                return result;
            }
        }

        public Pager(int page, int itemsPerPage, long totalItemsCount)
        {
            this.Page = page;
            this.ItemsPerPage = itemsPerPage;
            this.TotalItemsCount = totalItemsCount;
        }
    }
}

ProjectTimeLogger/ViewModels/UserModels.cs
using ProjectTimeLogger.Db.Models;
using ProjectTimeLogger.Db.Models.Search.Users;
using System.ComponentModel;

namespace ProjectTimeLogger.ViewModels
{
    public class UsersSearchModel : BaseSearchModel<Response, UsersSearchFormModel, User>
    {
        public Dictionary<uint, float> HoursByUserDict { get; set; }

        public UsersSearchModel(UsersSearchFormModel searchForm) : base(searchForm) { }
    }

    public class UsersSearchFormModel : BaseSearchFormModel
    {
        [DisplayName("Date From")]
        public DateTime? DateFrom { get; set; }

        [DisplayName("Date To")]
        public DateTime? DateTo { get; set; }

        public Request ToSearchRequest()
        {
            var request = new Request
            {
                DateFrom = this.DateFrom,
                DateTo = this.DateTo
            };

            this.SetSearchRequest(request);

            return request;
        }
    }
}

ProjectTimeLogger/Controllers/Api/BaseApiController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectTimeLogger.Controllers.Api
{
    [ApiController]
    public class BaseApiController : ControllerBase
    {
    }
}

ProjectTimeLogger/Controllers/Api/TimeLogsApiController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectTimeLogger.Db;
using ProjectTimeLogger.ViewModels.Api;

namespace ProjectTimeLogger.Controllers.Api
{
    [Route("/api/TimeLogs/[action]")]
    public class TimeLogsApiController : BaseApiController
    {
        [HttpGet]
        public IActionResult GetTotalHoursByUser(uint userId, DateTime? dateFrom, DateTime? dateTo)
        {
            var response = ProjectTimeLoggerDb.TimeLogs.GetTotalHoursByUser(userId, dateFrom, dateTo);

            return this.Ok(new TimeLogHoursModel { Name = response.User.FullName, Hours = response.TotalHours});
        }

        [HttpGet]
        public IActionResult GetTotalHoursByUsers(DateTime? dateFrom, DateTime? dateTo)
        {
            return this.Ok(ProjectTimeLoggerDb.TimeLogs.GetTotalHoursByUsers(dateFrom, dateTo, limit: 10).Select(r => new TimeLogHoursModel { Name = r.User.FullName, Hours = r.TotalHours}));
        }

        [HttpGet]
        public IActionResult GetTotalHoursByProjects(DateTime? dateFrom, DateTime? dateTo)
        {
            return this.Ok(ProjectTimeLoggerDb.TimeLogs.GetTotalHoursByProjects(dateFrom, dateTo).Select(r => new TimeLogHoursModel { Name = r.Project.Name, Hours = r.TotalHours }));
        }
    }
}

ProjectTimeLogger/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectTimeLogger.Db;
using ProjectTimeLogger.Models;
using ProjectTimeLogger.ViewModels;
using System.Diagnostics;

namespace ProjectTimeLogger.Controllers
{
    public class UsersController : Controller
    {
        public IActionResult Search(UsersSearchFormModel searchForm)
        {
            var model = new UsersSearchModel(searchForm)
            {
                Response = ProjectTimeLoggerDb.Users.Search(searchForm.ToSearchRequest())
            };

            if (model.Response.Records.Any())
            {
               model.HoursByUserDict = 
                    ProjectTimeLoggerDb.TimeLogs.GetTotalHoursByUsers(searchForm.DateFrom, searchForm.DateTo, userIds: model.Response.Records.Select(r => r.Id))
                    .ToDictionary(x => x.UserId, x => x.TotalHours);
            }

            return this.View(model);
        }

        public IActionResult ResetDb()
        {
            ProjectTimeLoggerDb.Initialize();

            return this.RedirectToAction(nameof(Search));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectTimeLogger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap-5.3.3-dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectTimeLogger.styles.css" asp-append-version="true" />
    <link href="~/fonts/fontawesome-6.7.2/css/all.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Users" asp-action="Search">ProjectTimeLogger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto"></ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a asp-action="ResetDB" asp-controller="Users" class="fs-4" title="Reset DB"><i class="fa-solid fa-rotate-right"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ProjectTimeLogger
        </div>
    </footer>

    <script src="~/lib/jquery-3.7.1/jquery-3.7.1.min.js"></script>
    <script src="~/lib/bootstrap-5.3.3-dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/google-charts/google-charts.js"></script>
    <script src="~/js/jquery-ajax-json.js" asp-append-version="true"></script>
    <script src="~/js/utils.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjectTimeLogger/Views/Shared/_PaginationPartial.cshtml
@model ProjectTimeLogger.ViewModels.Pager

@{
    var pageParam = "page";
    var controller = ViewContext.RouteData.Values["controller"].ToString();
    var action = ViewContext.RouteData.Values["action"].ToString();
    var query = System.Web.HttpUtility.ParseQueryString(this.Context.Request.QueryString.ToString());
}

<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item @(Model.Page > 1 ? "" : "disabled d-none")" ">
            <a class="page-link" href="@Url.Action(action, controller, queryString: query.AddOrSet(pageParam, (Model.Page - 1).ToString()))" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>

        @if (Model.DisplayedPages.First() > 1)
        {
            <li class="page-item disabled d-none d-md-inline-block">
                <a class="border-top-0 border-bottom-0 page-link bg-transparent" href="javascript:void(0)">...</a>
            </li>
        }

        @foreach (var page in Model.DisplayedPages)
        {
            <li class="page-item @(Model.Page == page ? "active" : "")"><a class="page-link" href="@Url.Action(action, controller, queryString: query.AddOrSet(pageParam, page.ToString()))">@(page)</a></li>
        }

        @if (Model.DisplayedPages.Last() < Model.PagesCount)
        {
            <li class="page-item disabled d-none d-md-inline-block">
                <a class="border-top-0 border-bottom-0 page-link bg-transparent" href="javascript:void(0)">...</a>
            </li>
        }

        <li class="page-item @(Model.Page < Model.PagesCount ? "" : "disabled d-none")">
            <a class="page-link" href="@Url.Action(action, controller, queryString: query.AddOrSet(pageParam, (Model.Page + 1).ToString()))" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>

ProjectTimeLogger/Views/Users/Search.cshtml
@model ProjectTimeLogger.ViewModels.UsersSearchModel

@{
    ViewBag.Title = "Users";
    var query = System.Web.HttpUtility.ParseQueryString(this.Context.Request.QueryString.ToString());
}

<h1 class="text-center">@ViewBag.Title (@Model.Response.TotalRecords)</h1>

<div class="row">
    <div class="col-md-6">
        <partial name="_SearchFormPartial" model="Model.SearchForm" />

        @if (!Model.Response.Records.Any())
        {
            <div role="alert" class="alert alert-info">There are no users found.</div>
        }
        else
        {
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col"><a href="@Url.Action(null, null, query.AddOrSet("sortBy", "u.first_name").AddOrSet("sortDesc", (!Model.SearchForm.SortDesc ?? false).ToString()))">First Name</a></th>
                        <th scope="col"><a href="@Url.Action(null, null, query.AddOrSet("sortBy", "u.last_name").AddOrSet("sortDesc", (!Model.SearchForm.SortDesc ?? false).ToString()))">Last Name</a></th>
                        <th scope="col"><a href="@Url.Action(null, null, query.AddOrSet("sortBy", "u.email").AddOrSet("sortDesc", (!Model.SearchForm.SortDesc ?? false).ToString()))">Email</a></th>
                        <th scope="col">Hours</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model.Response.Records)
                    {
                        <tr>
                            <td>@user.FirstName</td>
                            <td>@user.LastName</td>
                            <td>@user.Email</td>
                            <td>@Model.HoursByUserDict[user.Id].ToString("N2")</td>
                            <td class="text-nowrap">
                                <a class="compare-btn" data-user-id="@user.Id" title="Compare"><i class="fa-solid fa-shuffle"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <div>
                <div class="d-inline-block align-top mb-2 me-2">
                    <partial name="_PaginationPartial" model="Model.ToPager()" />
                </div>
            </div>
        }
    </div>

    @if (Model.Response.Records.Any())
    {
        <div class="col-md-6" id="chart-container">
            <div id="timelog-hours-chart"></div>
            <div class="text-end">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="chart-type-radio-btn" id="usersTypeBtn" checked>
                    <label class="form-check-label" for="flexRadioDefault1">
                        Users
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="chart-type-radio-btn" id="projectsTypeBtn">
                    <label class="form-check-label" for="flexRadioDefault2">
                        Projects
                    </label>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    <script>
        $(document).ready(function(){
             let data;
             let chart;

             google.charts.load('current', { packages: ['corechart'], callback: drawUsersChart});

             $("#usersTypeBtn").on("change", drawUsersChart);
             $("#projectsTypeBtn").on("change", drawProjectsChart);

             $(".compare-btn").on("click", function(){
                 let $this = $(this);
                 let userId = $this.data("user-id");

                 $.ajaxJson({
                     url: @Html.Raw(Json.Serialize(Url.Action("GetTotalHoursByUser", "TimeLogsApi"))),
                     data: { dateFrom: $("#DateFrom").val(), dateTo: $("#DateTo").val(), userId: userId },
                     success: function(res){
                         if (res){
                             if (data.getNumberOfColumns() == 2) {
                                 data.addColumn('number', res.name);
                                 data.addColumn({ type: 'string', role: 'tooltip' });
                             } else {
                               data.setColumnLabel(2, res.name);
                             }

                             for(var i = 0; i < data.getNumberOfRows(); i++){
                                data.setValue(i,2, res.hours);
                                data.setValue(i,3, "Hours:" + res.hours);
                             }

                             let options = {
                                 series: {
                                     1: { type: 'line', color: 'red', lineWidth: 2 },
                                 }
                             };

                             drawChart(options, data);
                         }
                     }
                 });
             });

             function drawUsersChart(){
                 getChartData(@Html.Raw(Json.Serialize(Url.Action("GetTotalHoursByUsers", "TimeLogsApi"))), function(res){
                     let options = {
                         title: 'Top 10 Users By Hours',
                         vAxis: {
                            title: 'User'
                         }
                     };

                     data = google.visualization.arrayToDataTable([['Name', 'Hours',], ...res.map(r => [r.name, r.hours])]);

                     drawChart(options);
                 });
             }

             function drawProjectsChart(){
                  getChartData(@Html.Raw(Json.Serialize(Url.Action("GetTotalHoursByProjects", "TimeLogsApi"))), function(res){
                     let options = {
                         title: 'Top Projects By Hours',
                         vAxis: {
                            title: 'Project'
                         }
                     };

                     data = google.visualization.arrayToDataTable([['Name', 'Hours',], ...res.map(r => [r.name, r.hours])]);

                     drawChart(options, data);
                  });
             }

             function getChartData(url, callback){
                 $.ajaxJson({
                     url: url,
                     data: { dateFrom: $("#DateFrom").val(), dateTo: $("#DateTo").val() },
                     success: function(res){
                         if (res && res.length > 0){
                             callback(res);
                         }
                     }
                 });
             }

             function drawChart(options){
                 let defaultOptions = {
                       height: $("#chart-container").height() - 50,
                       chartArea: {
                           height: '75%',
                           width: '55%'
                       },
                       hAxis: {
                         title: 'Total Hours',
                         minValue: 0
                       },
                       tooltip: { isHtml: true }
                 };

                 $.extend(true, options, defaultOptions);

                 if (!chart) { chart = new google.visualization.BarChart($("#timelog-hours-chart")[0]); }

                 chart.draw(data, options);
             }
         });
    </script>
}

ProjectTimeLogger/Views/Users/_SearchFormPartial.cshtml
@model ProjectTimeLogger.ViewModels.UsersSearchFormModel

<form method="get" id="search-form">
    <div class="row">
        <div class="col-md-4">
            <label asp-for="DateFrom" class="form-label"></label>
            <input asp-for="DateFrom" class="form-control" type="date" />
            <span asp-validation-for="DateFrom"></span>
        </div>

        <div class="col-md-4">
            <label asp-for="DateTo" class="form-label"></label>
            <input asp-for="DateTo" class="form-control" type="date" />
            <span asp-validation-for="DateTo"></span>
        </div>

        <div class="col-md-2  mb-2">
            <div>
                <label class="h6">&nbsp;</label>
                <div>
                    <input type="submit" value="Search" class="btn btn-info" />
                </div>
            </div>
        </div>
    </div>
</form>